import { Country, ResourceType, AssetType } from './types';

export const INITIAL_COUNTRIES: Country[] = [
  {
    id: 'usa',
    name: 'الولايات المتحدة',
    flag: '🇺🇸',
    isPlayer: false,
    isAlive: true,
    x: 15,
    y: 30,
    stats: {
      population: 331000000,
      economy: 21000,
      military: 95,
      resources: { [ResourceType.OIL]: 80, [ResourceType.GAS]: 90, [ResourceType.MINERALS]: 70 },
      happiness: 75,
      technology: 98,
      missiles: 50,
      ships: 10,
      deaths: 0,
      alliances: ['uk', 'canada', 'france', 'germany', 'japan', 'israel', 'saudi_arabia', 'qatar', 'uae'],
      sanctions: ['russia', 'iran', 'north_korea'],
      airDefense: 95,
    },
    regions: ['واشنطن العاصمة', 'نيويورك', 'لوس أنجلوس', 'تكساس', 'فلوريدا', 'كاليفورنيا', 'ألاسكا']
  },
  {
    id: 'china',
    name: 'الصين',
    flag: '🇨🇳',
    isPlayer: false,
    isAlive: true,
    x: 80,
    y: 35,
    stats: {
      population: 1400000000,
      economy: 15000,
      military: 90,
      resources: { [ResourceType.OIL]: 40, [ResourceType.GAS]: 30, [ResourceType.MINERALS]: 95 },
      happiness: 70,
      technology: 92,
      missiles: 40,
      ships: 8,
      deaths: 0,
      alliances: ['russia', 'pakistan', 'iran', 'north_korea'],
      sanctions: [],
      airDefense: 90,
    },
    regions: ['بكين', 'شنغهاي', 'هونج كونج', 'وهان', 'التبت', 'شينجيانغ', 'قوانغتشو']
  },
  {
    id: 'russia',
    name: 'روسيا',
    flag: '🇷🇺',
    isPlayer: false,
    isAlive: true,
    x: 70,
    y: 20,
    stats: {
      population: 145000000,
      economy: 1700,
      military: 85,
      resources: { [ResourceType.OIL]: 95, [ResourceType.GAS]: 98, [ResourceType.MINERALS]: 90 },
      happiness: 60,
      technology: 80,
      missiles: 45,
      ships: 6,
      deaths: 0,
      alliances: ['china', 'belarus', 'iran', 'syria'],
      sanctions: ['usa', 'uk', 'france', 'germany'],
      airDefense: 88,
    },
    regions: ['موسكو', 'سانت بطرسبرغ', 'سيبيريا', 'فلاديفوستوك', 'القرم', 'جبال الأورال']
  },
  {
    id: 'saudi_arabia',
    name: 'السعودية',
    flag: '🇸🇦',
    isPlayer: false,
    isAlive: true,
    x: 55,
    y: 45,
    stats: {
      population: 34000000,
      economy: 800,
      military: 70,
      resources: { [ResourceType.OIL]: 100, [ResourceType.GAS]: 80, [ResourceType.MINERALS]: 40 },
      happiness: 72,
      technology: 70,
      missiles: 20,
      ships: 4,
      deaths: 0,
      alliances: ['usa', 'uae', 'egypt', 'jordan', 'kuwait', 'bahrain'],
      sanctions: [],
      airDefense: 75,
    },
    regions: ['الرياض', 'جدة', 'مكة المكرمة', 'المدينة المنورة', 'المنطقة الشرقية', 'تبوك', 'عسير'],
    foreignAssets: [
      { id: 'qatar-base-saudi', ownerId: 'qatar', type: AssetType.BASE, name: 'قاعدة عسكرية قطرية', health: 100 }
    ]
  },
  {
    id: 'egypt',
    name: 'مصر',
    flag: '🇪🇬',
    isPlayer: false,
    isAlive: true,
    x: 50,
    y: 45,
    stats: {
      population: 100000000,
      economy: 360,
      military: 65,
      resources: { [ResourceType.OIL]: 40, [ResourceType.GAS]: 60, [ResourceType.MINERALS]: 30 },
      happiness: 55,
      technology: 50,
      missiles: 10,
      ships: 3,
      deaths: 0,
      alliances: ['saudi_arabia', 'uae', 'jordan'],
      sanctions: [],
      airDefense: 65,
    },
    regions: ['القاهرة', 'الإسكندرية', 'شبه جزيرة سيناء', 'الصعيد', 'مرسى مطروح', 'بورسعيد']
  },
  {
    id: 'qatar',
    name: 'قطر',
    flag: '🇶🇦',
    isPlayer: false,
    isAlive: true,
    x: 57,
    y: 46,
    stats: {
      population: 2800000,
      economy: 180,
      military: 40,
      resources: { [ResourceType.OIL]: 60, [ResourceType.GAS]: 100, [ResourceType.MINERALS]: 10 },
      happiness: 85,
      technology: 75,
      missiles: 5,
      deaths: 0,
      alliances: ['usa', 'turkey'],
      sanctions: [],
      airDefense: 60,
    },
    regions: ['الدوحة', 'الوكرة', 'الخور', 'الريان', 'مدينة الشمال'],
    foreignAssets: [
      { id: 'us-base-qatar', ownerId: 'usa', type: AssetType.BASE, name: 'قاعدة العديد الجوية', health: 100 }
    ]
  },
  {
    id: 'uae',
    name: 'الإمارات',
    flag: '🇦🇪',
    isPlayer: false,
    isAlive: true,
    x: 58,
    y: 47,
    stats: {
      population: 9800000,
      economy: 420,
      military: 60,
      resources: { [ResourceType.OIL]: 90, [ResourceType.GAS]: 70, [ResourceType.MINERALS]: 20 },
      happiness: 82,
      technology: 85,
      missiles: 15,
      deaths: 0,
      alliances: ['saudi_arabia', 'usa', 'egypt', 'israel'],
      sanctions: [],
      airDefense: 70,
    },
    regions: ['أبوظبي', 'دبي', 'الشارقة', 'العين', 'فجيرة', 'رأس الخيمة']
  },
  {
    id: 'kuwait',
    name: 'الكويت',
    flag: '🇰🇼',
    isPlayer: false,
    isAlive: true,
    x: 56,
    y: 44,
    stats: {
      population: 4200000,
      economy: 140,
      military: 35,
      resources: { [ResourceType.OIL]: 95, [ResourceType.GAS]: 50, [ResourceType.MINERALS]: 10 },
      happiness: 78,
      technology: 65,
      deaths: 0,
      alliances: ['saudi_arabia', 'usa'],
      sanctions: [],
      airDefense: 55,
    },
  },
  {
    id: 'iraq',
    name: 'العراق',
    flag: '🇮🇶',
    isPlayer: false,
    isAlive: true,
    x: 55,
    y: 42,
    stats: {
      population: 40000000,
      economy: 230,
      military: 55,
      resources: { [ResourceType.OIL]: 95, [ResourceType.GAS]: 40, [ResourceType.MINERALS]: 30 },
      happiness: 45,
      technology: 40,
      deaths: 0,
      alliances: ['iran'],
      sanctions: [],
      airDefense: 45,
    },
  },
  {
    id: 'iran',
    name: 'إيران',
    flag: '🇮🇷',
    isPlayer: false,
    isAlive: true,
    x: 60,
    y: 42,
    stats: {
      population: 83000000,
      economy: 450,
      military: 70,
      resources: { [ResourceType.OIL]: 90, [ResourceType.GAS]: 95, [ResourceType.MINERALS]: 70 },
      happiness: 50,
      technology: 65,
      missiles: 25,
      deaths: 0,
      alliances: ['russia', 'china', 'syria', 'iraq'],
      sanctions: ['usa', 'uk', 'france', 'germany', 'israel'],
      airDefense: 80,
    },
    regions: ['طهران', 'أصفهان', 'مشهد', 'شيراز', 'تبريز', 'بندر عباس', 'الأهواز'],
    foreignAssets: [
      { id: 'china-company-iran', ownerId: 'china', type: AssetType.COMPANY, name: 'شركة سينوبك للطاقة', health: 100 }
    ]
  },
  {
    id: 'israel',
    name: 'إسرائيل',
    flag: '🇮🇱',
    isPlayer: false,
    isAlive: true,
    x: 52,
    y: 42,
    stats: {
      population: 9000000,
      economy: 400,
      military: 85,
      resources: { [ResourceType.OIL]: 5, [ResourceType.GAS]: 70, [ResourceType.MINERALS]: 20 },
      happiness: 75,
      technology: 95,
      missiles: 30,
      deaths: 0,
      alliances: ['usa', 'uae'],
      sanctions: ['iran', 'syria', 'lebanon'],
      airDefense: 98,
    },
    regions: ['تل أبيب', 'القدس المحتلة', 'حيفا', 'صحراء النقب', 'إيلات']
  },
  {
    id: 'turkey',
    name: 'تركيا',
    flag: '🇹🇷',
    isPlayer: false,
    isAlive: true,
    x: 52,
    y: 38,
    stats: {
      population: 84000000,
      economy: 760,
      military: 75,
      resources: { [ResourceType.OIL]: 10, [ResourceType.GAS]: 15, [ResourceType.MINERALS]: 60 },
      happiness: 60,
      technology: 75,
      missiles: 12,
      deaths: 0,
      alliances: ['usa', 'qatar', 'uk', 'germany', 'france'],
      sanctions: [],
      airDefense: 78,
    },
  },
  {
    id: 'algeria',
    name: 'الجزائر',
    flag: '🇩🇿',
    isPlayer: false,
    isAlive: true,
    x: 45,
    y: 48,
    stats: {
      population: 43000000,
      economy: 170,
      military: 60,
      resources: { [ResourceType.OIL]: 80, [ResourceType.GAS]: 90, [ResourceType.MINERALS]: 50 },
      happiness: 62,
      technology: 55,
      deaths: 0,
      alliances: ['russia'],
      sanctions: [],
    },
  },
  {
    id: 'morocco',
    name: 'المغرب',
    flag: '🇲🇦',
    isPlayer: false,
    isAlive: true,
    x: 40,
    y: 48,
    stats: {
      population: 36000000,
      economy: 120,
      military: 55,
      resources: { [ResourceType.OIL]: 5, [ResourceType.GAS]: 5, [ResourceType.MINERALS]: 95 },
      happiness: 68,
      technology: 60,
      deaths: 0,
      alliances: ['usa', 'france'],
      sanctions: [],
    },
  },
  {
    id: 'jordan',
    name: 'الأردن',
    flag: '🇯🇴',
    isPlayer: false,
    isAlive: true,
    x: 53,
    y: 43,
    stats: {
      population: 10000000,
      economy: 45,
      military: 50,
      resources: { [ResourceType.OIL]: 2, [ResourceType.GAS]: 5, [ResourceType.MINERALS]: 40 },
      happiness: 65,
      technology: 60,
      deaths: 0,
      alliances: ['usa', 'saudi_arabia', 'egypt'],
      sanctions: [],
    },
  },
  {
    id: 'syria',
    name: 'سوريا',
    flag: '🇸🇾',
    isPlayer: false,
    isAlive: true,
    x: 54,
    y: 40,
    stats: {
      population: 17000000,
      economy: 20,
      military: 45,
      resources: { [ResourceType.OIL]: 30, [ResourceType.GAS]: 20, [ResourceType.MINERALS]: 20 },
      happiness: 30,
      technology: 40,
      deaths: 0,
      alliances: ['russia', 'iran'],
      sanctions: ['usa', 'uk', 'france', 'germany', 'israel', 'turkey'],
    },
  },
  {
    id: 'lebanon',
    name: 'لبنان',
    flag: '🇱🇧',
    isPlayer: false,
    isAlive: true,
    x: 53,
    y: 41,
    stats: {
      population: 6800000,
      economy: 30,
      military: 30,
      resources: { [ResourceType.OIL]: 5, [ResourceType.GAS]: 20, [ResourceType.MINERALS]: 10 },
      happiness: 35,
      technology: 55,
      deaths: 0,
      alliances: ['iran', 'france'],
      sanctions: ['israel'],
    },
  },
  {
    id: 'oman',
    name: 'عمان',
    flag: '🇴🇲',
    isPlayer: false,
    isAlive: true,
    x: 60,
    y: 50,
    stats: {
      population: 5000000,
      economy: 75,
      military: 45,
      resources: { [ResourceType.OIL]: 85, [ResourceType.GAS]: 70, [ResourceType.MINERALS]: 30 },
      happiness: 75,
      technology: 60,
      deaths: 0,
      alliances: ['usa', 'saudi_arabia'],
      sanctions: [],
    },
  },
  {
    id: 'bahrain',
    name: 'البحرين',
    flag: '🇧🇭',
    isPlayer: false,
    isAlive: true,
    x: 57,
    y: 45,
    stats: {
      population: 1700000,
      economy: 38,
      military: 30,
      resources: { [ResourceType.OIL]: 40, [ResourceType.GAS]: 30, [ResourceType.MINERALS]: 5 },
      happiness: 72,
      technology: 65,
      deaths: 0,
      alliances: ['usa', 'saudi_arabia'],
      sanctions: [],
    },
  },
  {
    id: 'tunisia',
    name: 'تونس',
    flag: '🇹🇳',
    isPlayer: false,
    isAlive: true,
    x: 48,
    y: 42,
    stats: {
      population: 11000000,
      economy: 40,
      military: 35,
      resources: { [ResourceType.OIL]: 10, [ResourceType.GAS]: 10, [ResourceType.MINERALS]: 60 },
      happiness: 58,
      technology: 60,
      deaths: 0,
      alliances: ['france'],
      sanctions: [],
    },
  },
  {
    id: 'libya',
    name: 'ليبيا',
    flag: '🇱🇾',
    isPlayer: false,
    isAlive: true,
    x: 48,
    y: 48,
    stats: {
      population: 6800000,
      economy: 45,
      military: 40,
      resources: { [ResourceType.OIL]: 98, [ResourceType.GAS]: 90, [ResourceType.MINERALS]: 30 },
      happiness: 40,
      technology: 35,
      deaths: 0,
      alliances: ['turkey', 'russia'],
      sanctions: [],
    },
  },
  {
    id: 'sudan',
    name: 'السودان',
    flag: '🇸🇩',
    isPlayer: false,
    isAlive: true,
    x: 52,
    y: 55,
    stats: {
      population: 43000000,
      economy: 35,
      military: 50,
      resources: { [ResourceType.OIL]: 60, [ResourceType.GAS]: 10, [ResourceType.MINERALS]: 80 },
      happiness: 35,
      technology: 30,
      deaths: 0,
      alliances: [],
      sanctions: [],
    },
  },
  {
    id: 'yemen',
    name: 'اليمن',
    flag: '🇾🇪',
    isPlayer: false,
    isAlive: true,
    x: 58,
    y: 55,
    stats: {
      population: 29000000,
      economy: 25,
      military: 35,
      resources: { [ResourceType.OIL]: 40, [ResourceType.GAS]: 30, [ResourceType.MINERALS]: 20 },
      happiness: 25,
      technology: 20,
      deaths: 0,
      alliances: ['iran', 'saudi_arabia'],
      sanctions: [],
    },
  },
  {
    id: 'palestine',
    name: 'فلسطين',
    flag: '🇵🇸',
    isPlayer: false,
    isAlive: true,
    x: 52,
    y: 43,
    stats: {
      population: 5000000,
      economy: 15,
      military: 20,
      resources: { [ResourceType.OIL]: 0, [ResourceType.GAS]: 30, [ResourceType.MINERALS]: 10 },
      happiness: 30,
      technology: 45,
      deaths: 0,
      alliances: ['egypt', 'jordan', 'turkey', 'iran'],
      sanctions: ['israel'],
    },
    regions: ['القدس الشريف', 'قطاع غزة الصامد', 'الضفة الغربية', 'رام الله', 'جنين', 'نابلس', 'الخليل']
  },
  {
    id: 'uk',
    name: 'المملكة المتحدة',
    flag: '🇬🇧',
    isPlayer: false,
    isAlive: true,
    x: 45,
    y: 25,
    stats: {
      population: 67000000,
      economy: 3100,
      military: 750,
      resources: { [ResourceType.OIL]: 10, [ResourceType.GAS]: 15, [ResourceType.MINERALS]: 20 },
      happiness: 75,
      technology: 90,
      missiles: 25,
      deaths: 0,
      alliances: ['usa', 'france', 'germany'],
      sanctions: []
    }
  },
  {
    id: 'france',
    name: 'فرنسا',
    flag: '🇫🇷',
    isPlayer: false,
    isAlive: true,
    x: 46,
    y: 30,
    stats: {
      population: 68000000,
      economy: 2900,
      military: 800,
      resources: { [ResourceType.OIL]: 5, [ResourceType.GAS]: 5, [ResourceType.MINERALS]: 30 },
      happiness: 70,
      technology: 92,
      missiles: 20,
      deaths: 0,
      alliances: ['usa', 'uk', 'germany'],
      sanctions: []
    }
  },
  {
    id: 'germany',
    name: 'ألمانيا',
    flag: '🇩🇪',
    isPlayer: false,
    isAlive: true,
    x: 48,
    y: 28,
    stats: {
      population: 84000000,
      economy: 4200,
      military: 600,
      resources: { [ResourceType.OIL]: 2, [ResourceType.GAS]: 5, [ResourceType.MINERALS]: 40 },
      happiness: 80,
      technology: 95,
      missiles: 15,
      deaths: 0,
      alliances: ['usa', 'uk', 'france'],
      sanctions: []
    },
    foreignAssets: [
      { id: 'us-base-germany', ownerId: 'usa', type: AssetType.BASE, name: 'قاعدة رامشتاين الجوية', health: 100 },
      { id: 'us-company-germany', ownerId: 'usa', type: AssetType.COMPANY, name: 'مجمع سيمنز التكنولوجي المشترك', health: 100 }
    ]
  },
  {
    id: 'japan',
    name: 'اليابان',
    flag: '🇯🇵',
    isPlayer: false,
    isAlive: true,
    x: 90,
    y: 35,
    stats: {
      population: 125000000,
      economy: 4900,
      military: 550,
      resources: { [ResourceType.OIL]: 1, [ResourceType.GAS]: 1, [ResourceType.MINERALS]: 10 },
      happiness: 75,
      technology: 98,
      missiles: 10,
      deaths: 0,
      alliances: ['usa'],
      sanctions: []
    }
  },
  {
    id: 'india',
    name: 'الهند',
    flag: '🇮🇳',
    isPlayer: false,
    isAlive: true,
    x: 75,
    y: 50,
    stats: {
      population: 1400000000,
      economy: 3400,
      military: 1500,
      resources: { [ResourceType.OIL]: 15, [ResourceType.GAS]: 10, [ResourceType.MINERALS]: 70 },
      happiness: 60,
      technology: 75,
      missiles: 40,
      deaths: 0,
      alliances: ['russia'],
      sanctions: []
    }
  },
  {
    id: 'brazil',
    name: 'البرازيل',
    flag: '🇧🇷',
    isPlayer: false,
    isAlive: true,
    x: 25,
    y: 70,
    stats: {
      population: 215000000,
      economy: 1900,
      military: 400,
      resources: { [ResourceType.OIL]: 50, [ResourceType.GAS]: 30, [ResourceType.MINERALS]: 85 },
      happiness: 65,
      technology: 60,
      deaths: 0,
      alliances: [],
      sanctions: []
    }
  },
  {
    id: 'canada',
    name: 'كندا',
    flag: '🇨🇦',
    isPlayer: false,
    isAlive: true,
    x: 15,
    y: 15,
    stats: {
      population: 39000000,
      economy: 2100,
      military: 300,
      resources: { [ResourceType.OIL]: 80, [ResourceType.GAS]: 70, [ResourceType.MINERALS]: 90 },
      happiness: 85,
      technology: 88,
      deaths: 0,
      alliances: ['usa', 'uk'],
      sanctions: []
    }
  },
  {
    id: 'australia',
    name: 'أستراليا',
    flag: '🇦🇺',
    isPlayer: false,
    isAlive: true,
    x: 85,
    y: 80,
    stats: {
      population: 26000000,
      economy: 1700,
      military: 350,
      resources: { [ResourceType.OIL]: 20, [ResourceType.GAS]: 60, [ResourceType.MINERALS]: 95 },
      happiness: 82,
      technology: 85,
      deaths: 0,
      alliances: ['usa', 'uk'],
      sanctions: []
    }
  },
  {
    id: 'south_korea',
    name: 'كوريا الجنوبية',
    flag: '🇰🇷',
    isPlayer: false,
    isAlive: true,
    x: 85,
    y: 35,
    stats: {
      population: 52000000,
      economy: 1800,
      military: 900,
      resources: { [ResourceType.OIL]: 1, [ResourceType.GAS]: 1, [ResourceType.MINERALS]: 15 },
      happiness: 70,
      technology: 96,
      deaths: 0,
      alliances: ['usa'],
      sanctions: []
    }
  },
  {
    id: 'italy',
    name: 'إيطاليا',
    flag: '🇮🇹',
    isPlayer: false,
    isAlive: true,
    x: 48,
    y: 35,
    stats: {
      population: 59000000,
      economy: 2100,
      military: 450,
      resources: { [ResourceType.OIL]: 5, [ResourceType.GAS]: 5, [ResourceType.MINERALS]: 25 },
      happiness: 72,
      technology: 85,
      deaths: 0,
      alliances: ['usa', 'france', 'germany'],
      sanctions: []
    }
  },
  {
    id: 'spain',
    name: 'إسبانيا',
    flag: '🇪🇸',
    isPlayer: false,
    isAlive: true,
    x: 44,
    y: 35,
    stats: {
      population: 47000000,
      economy: 1400,
      military: 300,
      resources: { [ResourceType.OIL]: 2, [ResourceType.GAS]: 2, [ResourceType.MINERALS]: 20 },
      happiness: 75,
      technology: 80,
      deaths: 0,
      alliances: ['usa', 'france', 'germany'],
      sanctions: []
    }
  },
  {
    id: 'mexico',
    name: 'المكسيك',
    flag: '🇲🇽',
    isPlayer: false,
    isAlive: true,
    x: 15,
    y: 45,
    stats: {
      population: 128000000,
      economy: 1400,
      military: 250,
      resources: { [ResourceType.OIL]: 40, [ResourceType.GAS]: 20, [ResourceType.MINERALS]: 60 },
      happiness: 60,
      technology: 55,
      deaths: 0,
      alliances: ['usa'],
      sanctions: []
    }
  },
  {
    id: 'indonesia',
    name: 'إندونيسيا',
    flag: '🇮🇩',
    isPlayer: false,
    isAlive: true,
    x: 85,
    y: 65,
    stats: {
      population: 275000000,
      economy: 1300,
      military: 400,
      resources: { [ResourceType.OIL]: 30, [ResourceType.GAS]: 40, [ResourceType.MINERALS]: 70 },
      happiness: 65,
      technology: 50,
      deaths: 0,
      alliances: [],
      sanctions: []
    }
  },
  {
    id: 'netherlands',
    name: 'هولندا',
    flag: '🇳🇱',
    isPlayer: false,
    isAlive: true,
    x: 47,
    y: 26,
    stats: {
      population: 175000000,
      economy: 1000,
      military: 200,
      resources: { [ResourceType.OIL]: 5, [ResourceType.GAS]: 40, [ResourceType.MINERALS]: 10 },
      happiness: 88,
      technology: 92,
      deaths: 0,
      alliances: ['usa', 'germany', 'uk'],
      sanctions: []
    }
  },
  {
    id: 'switzerland',
    name: 'سويسرا',
    flag: '🇨🇭',
    isPlayer: false,
    isAlive: true,
    x: 47,
    y: 32,
    stats: {
      population: 8700000,
      economy: 800,
      military: 150,
      resources: { [ResourceType.OIL]: 0, [ResourceType.GAS]: 0, [ResourceType.MINERALS]: 10 },
      happiness: 92,
      technology: 95,
      deaths: 0,
      alliances: [],
      sanctions: []
    }
  },
  {
    id: 'pakistan',
    name: 'باكستان',
    flag: '🇵🇰',
    isPlayer: false,
    isAlive: true,
    x: 70,
    y: 45,
    stats: {
      population: 235000000,
      economy: 350,
      military: 1200,
      resources: { [ResourceType.OIL]: 5, [ResourceType.GAS]: 15, [ResourceType.MINERALS]: 40 },
      happiness: 50,
      technology: 45,
      deaths: 0,
      alliances: ['china', 'saudi_arabia'],
      sanctions: []
    }
  }
];
